List<String> allAdvices = [
  "Maintain a healthy diet",
  "Exercise regularly",
  "Get adequate sleep (7-8 hours)",
  "Drink plenty of water",
  "Reduce stress through relaxation techniques",
  "Avoid smoking and alcohol",
  "Monitor blood pressure regularly",
  "Take medications as prescribed",
  "Follow up in 2 weeks",
  "Get a blood test done",
  "Limit caffeine intake",
  "Maintain a balanced work-life schedule",
  "Wear sunscreen when outdoors",
  "Follow a low-salt diet",
  "Practice deep breathing exercises",
  "Keep a symptom diary",
  "Avoid exposure to allergens",
  "Schedule a follow-up appointment",
  "Get vaccinated (flu, COVID-19, etc.)",
  "Adhere to a diabetic-friendly diet",
  "Use prescribed glasses/contact lenses",
  "Limit screen time",
  "Elevate legs to reduce swelling",
  "Take breaks during long sitting periods",
  "Avoid strenuous activity",
  "Consult a specialist if symptoms persist",
  "Undergo physiotherapy",
  "Rest until recovery",
  "Take iron supplements if needed",
  "Monitor glucose levels regularly",
  "Avoid processed foods",
  "Take probiotics for gut health",
  "Apply cold compresses for swelling",
  "Maintain personal hygiene",
  "Keep wounds clean and dry",
  "Use a humidifier at night",
  "Follow a low-fat diet",
  "Avoid crowded places during flu season",
  "Get an annual health check-up",
  "Take calcium supplements",
  "Use an inhaler if breathing worsens",
  "Practice good posture",
  "Limit sodium intake",
  "Monitor weight weekly",
  "Avoid self-medication",
  "Use a CPAP machine if diagnosed with sleep apnea",
  "Get screened for cholesterol levels",
  "Attend mental health counseling if needed",
  "Avoid fast food and sugary drinks",
  "Wear comfortable shoes",
  "Keep active with light exercise",
  "Seek emergency care if symptoms worsen",
  "Avoid sharing personal items",
  "Practice safe sex",
  "Undergo regular dental check-ups",
  "Avoid greasy foods",
  "Get enough sunlight for Vitamin D",
  "Continue physical activity after recovery",
  "Use over-the-counter medication if necessary",
  "Avoid using electronic devices before bed",
  "Get regular eye check-ups",
  "Wash hands frequently",
  "Avoid heavy lifting",
  "Wear protective gear during activities",
  "Check for food intolerances",
  "Use earplugs in noisy environments",
  "Avoid dairy if lactose intolerant",
  "Keep blood sugar under control",
  "Limit alcohol to special occasions",
  "Try yoga or meditation",
  "Use pain relief medication only as directed",
  "Take regular breaks from physical labor",
  "Apply ointment to rashes",
  "Monitor thyroid function regularly",
  "Avoid late-night snacking",
  "Track menstrual cycle",
  "Increase fiber intake",
  "Seek professional help for anxiety",
  "Keep a log of allergic reactions",
  "Get regular mammograms or Pap smears",
  "Use a walking aid if required",
  "Keep up-to-date with vaccinations",
  "Consult a dietitian for weight management",
  "Attend a rehabilitation program if needed",
  "Limit sugar intake",
  "Avoid prolonged exposure to screens",
  "Stretch before and after exercise",
  "Schedule annual physical exams",
  "Use ice packs for pain relief",
  "Switch to ergonomic furniture",
  "Try a low-carb diet if recommended",
  "Take vitamin supplements as needed",
  "Avoid second-hand smoke",
  "Wear a mask in polluted environments",
  "Disinfect surfaces frequently",
  "Follow prescribed rehabilitation exercises",
  "Use a heating pad for muscle pain",
  "Wear compression stockings if advised",
  "Avoid direct sunlight if photosensitive",
  "Take a multivitamin daily if recommended",
  "Limit gluten if intolerant",
  "Use antibacterial soap",
  "Practice portion control during meals",
];