List<String> allComplaints = [
  "Abdominal pain",
  "Acid reflux",
  "Acne",
  "Allergic reaction",
  "Ankle pain",
  "Anxiety",
  "Arm pain",
  "Back pain",
  "Bad breath",
  "Balance problems",
  "Bloating",
  "Blurry vision",
  "Breast pain",
  "Breathing difficulty",
  "Bruising easily",
  "Burning sensation",
  "Chest pain",
  "Chills",
  "Cold hands and feet",
  "Cold sweats",
  "Confusion",
  "Constipation",
  "Coughing",
  "Cramps",
  "Dark urine",
  "Dehydration",
  "Dementia",
  "Depression",
  "Diarrhea",
  "Dizziness",
  "Double vision",
  "Dry eyes",
  "Dry mouth",
  "Ear pain",
  "Ear ringing",
  "Excessive sweating",
  "Eye pain",
  "Facial pain",
  "Fatigue",
  "Fever",
  "Flashing lights in vision",
  "Frequent urination",
  "Hair loss",
  "Hallucinations",
  "Headache",
  "Heart palpitations",
  "Heartburn",
  "Hearing loss",
  "Hemorrhoids",
  "High blood pressure",
  "Hoarseness",
  "Hot flashes",
  "Inability to concentrate",
  "Indigestion",
  "Insomnia",
  "Itching",
  "Joint pain",
  "Jumpy vision",
  "Leg cramps",
  "Leg pain",
  "Lightheadedness",
  "Low blood pressure",
  "Memory loss",
  "Mood swings",
  "Mouth sores",
  "Muscle aches",
  "Muscle weakness",
  "Nausea",
  "Nervousness",
  "Night sweats",
  "Numbness",
  "Painful urination",
  "Palpitations",
  "Pelvic pain",
  "Rash",
  "Red eyes",
  "Restlessness",
  "Runny nose",
  "Seizures",
  "Sensitivity to light",
  "Shakiness",
  "Shortness of breath",
  "Shoulder pain",
  "Sinus congestion",
  "Skin rash",
  "Slurred speech",
  "Sore throat",
  "Sore tongue",
  "Spitting up blood",
  "Stomach cramps",
  "Stomach pain",
  "Swallowing difficulties",
  "Sweating",
  "Swelling",
  "Tingling sensation",
  "Tiredness",
  "Toothache",
  "Tremors",
  "Trouble breathing",
  "Trouble sleeping",
  "Unintentional weight loss",
  "Urinary incontinence",
  "Vaginal discharge",
  "Vision problems",
  "Vomiting",
  "Weakness",
  "Weight gain",
  "Wheezing",
  "Yellowing of the skin",
  "Abscess",
  "Acute pain",
  "Alopecia",
  "Angina",
  "Anorexia",
  "Aphasia",
  "Appendicitis",
  "Arrhythmia",
  "Arthritis",
  "Asthma",
  "Ataxia",
  "Back stiffness",
  "Bipolar disorder",
  "Bleeding gums",
  "Blindness",
  "Blood in stool",
  "Blood in urine",
  "Blurred vision",
  "Bone pain",
  "Burning eyes",
  "Cancer pain",
  "Carpal tunnel syndrome",
  "Cataracts",
  "Change in bowel habits",
  "Chills and fever",
  "Chronic fatigue",
  "Chronic pain",
  "Clammy skin",
  "Cold intolerance",
  "Congestion",
  "Cyanosis",
  "Cystic acne",
  "Decreased appetite",
  "Decreased urine output",
  "Dental abscess",
  "Diabetic symptoms",
  "Difficulty hearing",
  "Disorientation",
  "Disrupted sleep",
  "Dry scalp",
  "Ear discharge",
  "Ear infection",
  "Eye strain",
  "Facial drooping",
  "Facial swelling",
  "Falls",
  "Fainting",
  "Flu-like symptoms",
  "Fluid retention",
  "Frequent headaches",
  "Gallbladder pain",
  "General discomfort",
  "Glaucoma",
  "Gout pain",
  "Heart murmur",
  "Hemoptysis",
  "High fever",
  "Hyperventilation",
  "Impaired coordination",
  "Incontinence",
  "Inflamed gums",
  "Involuntary movements",
  "Irregular heartbeat",
  "Jaundice",
  "Joint stiffness",
  "Kidney pain",
  "Liver pain",
  "Loose stools",
  "Loss of appetite",
  "Loss of consciousness",
  "Low-grade fever",
  "Lump in throat",
  "Menstrual pain",
  "Menstrual irregularities",
  "Migraines",
  "Morning stiffness",
  "Motion sickness",
  "Muscle cramping",
  "Neck pain",
  "Nosebleed",
  "Ocular pain",
  "Onset of anxiety",
  "Pain during sex",
  "Pain in flank",
  "Pain in groin",
  "Pancreatic pain",
  "Paresthesia",
  "Persistent cough",
  "Phantom pain",
  "Post-surgery pain",
  "Profuse sweating",
  "Prolonged fatigue",
  "Psoriasis flares",
  "Rectal bleeding",
  "Respiratory distress",
  "Severe headache",
  "Short-term memory loss",
  "Skin lesions",
  "Sleep disturbances",
  "Spinal pain",
  "Stiff neck",
  "Sudden chest pain",
  "Swelling in limbs",
  "Swollen lymph nodes",
  "Tachycardia",
  "Tearing eyes",
  "Throat discomfort",
  "Thyroid pain",
  "Tingling in hands",
  "Ulcers",
  "Uncontrolled movements",
  "Upper abdominal pain",
  "Urinary retention",
  "Vascular pain",
  "Vomiting blood",
  "Water retention",
  "Watery eyes",
  "Weak pulse",
  "Weakness in limbs",
  "Wheezing cough",
  "Wrinkles",
  "Zoster pain"
];