List<String> allDiagnosis = [
  "Abdominal aortic aneurysm",
  "Achilles tendinopathy",
  "Acne",
  "Acute cholecystitis",
  "Acute lymphoblastic leukaemia",
  "Acute myeloid leukaemia",
  "Acute pancreatitis",
  "Addisonâ€™s disease",
  "Adenomyosis",
  "Allergic rhinitis",
  "Alcohol-related liver disease",
  "Allergies",
  "Alzheimerâ€™s disease",
  "Anal cancer",
  "Anaphylaxis",
  "Angina",
  "Angioedema",
  "Ankle sprain",
  "Ankylosing spondylitis",
  "Anorexia nervosa",
  "Anxiety",
  "Anxiety disorders in children",
  "Appendicitis",
  "Arterial thrombosis",
  "Arthritis",
  "Asbestosis",
  "Asthma",
  "Ataxia",
  "Atopic eczema",
  "Atrial fibrillation",
  "Attention deficit hyperactivity disorder (ADHD)",
  "Autistic spectrum disorder (ASD)",
  "Bacterial vaginosis",
  "Benign prostate enlargement",
  "Bile duct cancer (cholangiocarcinoma)",
  "Binge eating",
  "Bipolar disorder",
  "Bladder cancer",
  "Blood poisoning (sepsis)",
  "Bone cancer",
  "Bone cancer: Teenagers and young adults",
  "Bowel cancer",
  "Bowel incontinence",
  "Bowel polyps",
  "Brain stem death",
  "Brain tumours",
  "Breast cancer",
  "Bronchiectasis",
  "Bronchitis",
  "Bulimia",
  "Bunion",
  "Carcinoid syndrome and carcinoid tumours",
  "Cardiovascular disease",
  "Carpal tunnel syndrome",
  "Catarrh",
  "Cellulitis",
  "Cerebral palsy",
  "Cervical cancer",
  "Cervical spondylosis",
  "Chest and rib injury",
  "Chest infection",
  "Chickenpox",
  "Chilblains",
  "Chlamydia",
  "Chronic fatigue syndrome",
  "Chronic kidney disease",
  "Chronic lymphocytic leukaemia",
  "Chronic myeloid leukaemia",
  "Chronic obstructive pulmonary disease (COPD)",
  "Chronic pain",
  "Chronic pancreatitis",
  "Cirrhosis",
  "Clostridium difficile",
  "Coeliac disease",
  "Cold sore",
  "Coma",
  "Common cold",
  "Congenital heart disease",
  "Conjunctivitis",
  "Constipation",
  "Coronary heart disease",
  "Coronavirus (COVID-19)",
  "Costochondritis",
  "Cough",
  "Crohnâ€™s disease",
  "Croup",
  "Cystic fibrosis",
  "Cystitis",
  "Deafblindness",
  "Deep vein thrombosis",
  "Degenerative Cervical Myelopathy",
  "Dehydration",
  "Delirium",
  "Dementia",
  "Dental abscess",
  "Depression",
  "Dermatitis herpetiformis",
  "Diabetes",
  "Diabetic retinopathy",
  "Diarrhoea",
  "Discoid eczema",
  "Diverticular disease and diverticulitis",
  "Dizziness (Lightheadedness)",
  "Downâ€™s syndrome",
  "Dry mouth",
  "Dysphagia (swallowing problems)",
  "Dystonia",
  "Earache",
  "Earwax build-up",
  "Ebola virus disease",
  "Ectopic pregnancy",
  "Edwardsâ€™ syndrome",
  "Endometriosis",
  "Epilepsy",
  "Erectile dysfunction (impotence)",
  "Escherichia coli (E. coli) O157",
  "Ewing sarcoma",
  "Ewing sarcoma: Children",
  "Eye cancer",
  "Farting",
  "Febrile seizures",
  "Feeling of something in your throat (Globus)",
  "Fever in adults",
  "Fever in children",
  "Fibroids",
  "Fibromyalgia",
  "Flu",
  "Foetal alcohol syndrome",
  "Food allergy",
  "Food poisoning",
  "Frozen shoulder",
  "Functional neurological disorder (FND)",
  "Fungal nail infection",
  "Gallbladder cancer",
  "Gallstones",
  "Ganglion cyst",
  "Gastroenteritis",
  "Gastro-oesophageal reflux disease (GORD)",
  "Genital herpes",
  "Genital symptoms",
  "Genital warts",
  "Germ cell tumours",
  "Glandular fever",
  "Golfers elbow",
  "Gonorrhoea",
  "Gout",
  "Greater trochanteric pain syndrome",
  "Gum disease",
  "Haemorrhoids (piles)",
  "Hand, foot and mouth disease",
  "Hay fever",
  "Head and neck cancer",
  "Head lice and nits",
  "Headaches",
  "Hearing loss",
  "Heart attack",
  "Heart block",
  "Heart failure",
  "Heart palpitations",
  "Hepatitis A",
  "Hepatitis B",
  "Hepatitis C",
  "Hiatus hernia",
  "High blood pressure (hypertension)",
  "High cholesterol",
  "HIV",
  "Hodgkin lymphoma",
  "Hodgkin lymphoma",
  "Huntingtonâ€™s disease",
  "Hyperglycaemia",
  "Idiopathic pulmonary fibrosis",
  "If your child has cold or flu symptoms",
  "Impetigo",
  "Indigestion",
  "Ingrown toenail",
  "Infertility",
  "Inflammatory bowel disease (IBD)",
  "Inherited heart conditions",
  "Insomnia",
  "Iron deficiency anaemia",
  "Irritable bowel syndrome (IBS)",
  "Itching",
  "Itchy bottom",
  "Itchy skin",
  "Joint hypermobility",
  "Kaposiâ€™s sarcoma",
  "Kidney cancer",
  "Kidney infection",
  "Kidney stones",
  "Labyrinthitis",
  "Lactose intolerance",
  "Laryngeal (larynx) cancer",
  "Laryngitis",
  "Leg cramps",
  "Lichen planus",
  "Lipoedema",
  "Liver cancer",
  "Liver disease",
  "Liver tumours",
  "Long-term effects of COVID-19",
  "Loss of libido",
  "Low blood pressure (hypotension)",
  "Lumbar stenosis",
  "Lung cancer",
  "Lupus",
  "Lyme disease",
  "Lymphoedema",
  "Lymphogranuloma venereum (LGV)",
  "Malaria",
  "Malignant brain tumour (cancerous)",
  "Malnutrition",
  "Managing genital symptoms",
  "Measles",
  "Meningitis",
  "Meniereâ€™s disease",
  "Menopause",
  "Mesothelioma",
  "Middle ear infection (otitis media)",
  "Migraine",
  "Miscarriage",
  "Motor neurone disease (MND)",
  "Mouth cancer",
  "Mouth ulcer",
  "Multiple myeloma",
  "Multiple sclerosis (MS)",
  "Multiple system atrophy (MSA)",
  "Mumps",
  "Munchausenâ€™s syndrome",
  "Myalgic encephalomyelitis (ME) or chronic fatigue syndrome (CFS)",
  "Myasthenia gravis",
  "Nasal and sinus cancer",
  "Nasopharyngeal cancer",
  "Neck problems",
  "Neuroendocrine tumours",
  "Non-alcoholic fatty liver disease (NAFLD)",
  "Non-Hodgkin lymphoma",
  "Norovirus",
  "Nosebleed",
  "Obesity",
  "Obsessive compulsive disorder (OCD)",
  "Obstructive sleep apnoea",
  "Oesophageal cancer",
  "Oral thrush in adults",
  "Osteoarthritis",
  "Osteoarthritis of the hip",
  "Osteoarthritis of the knee",
  "Osteoarthritis of the thumb",
  "Osteoporosis",
  "Osteosarcoma",
  "Outer ear infection (otitis externa)",
  "Ovarian cancer",
  "Ovarian cancer: Teenagers and young adults",
  "Ovarian cyst",
  "Overactive thyroid",
  "Pain in the ball of the foot",
  "Pagetâ€™s disease of the nipple",
  "Pancreatic cancer",
  "Panic disorder",
  "Parkinsonâ€™s disease",
  "Patauâ€™s syndrome",
  "Patellofemoral pain syndrome",
  "Pelvic inflammatory disease",
  "Pelvic organ prolapse",
  "Penile cancer",
  "Peripheral neuropathy",
  "Personality disorder",
  "PIMS",
  "Plantar heel pain",
  "Pleurisy",
  "Pneumonia",
  "Polio",
  "Polycystic ovary syndrome (PCOS)",
  "Polymyalgia rheumatica",
  "Post-polio syndrome",
  "Post-traumatic stress disorder (PTSD)",
  "Postural orthostatic tachycardia syndrome (PoTS)",
  "Pre-eclampsia",
  "Pressure ulcers",
  "Progressive supranuclear palsy (PSP)",
  "Prostate cancer",
  "Psoriasis",
  "Psoriatic arthritis",
  "Psychosis",
  "Pubic lice",
  "Pulmonary hypertension",
  "Rare conditions",
  "Rare tumours",
  "Raynaudâ€™s phenomenon",
  "Reactive arthritis",
  "Restless legs syndrome",
  "Respiratory syncytial virus (RSV)",
  "Retinoblastoma",
  "Rhabdomyosarcoma",
  "Rheumatoid arthritis",
  "Ringworm and other fungal infections",
  "Rosacea",
  "Scabies",
  "Scarlet fever",
  "Schizophrenia",
  "Sciatica",
  "Scoliosis",
  "Seasonal affective disorder (SAD)",
  "Sepsis",
  "Septic shock",
  "Shingles",
  "Shortness of breath",
  "Sickle cell disease",
  "Sinusitis",
  "Sjogrenâ€™s syndrome",
  "Skin cancer (melanoma)",
  "Skin cancer (non-melanoma)",
  "Skin light sensitivity (photosensitivity)",
  "Skin rashes in children",
  "Slapped cheek syndrome",
  "Soft tissue sarcomas",
  "Soft tissue sarcomas: Teenagers and young adults",
  "Sore throat",
  "Spleen problems and spleen removal",
  "Stillbirth",
  "Stomach ache and abdominal pain",
  "Stomach cancer",
  "Stomach ulcer",
  "Streptococcus A (strep A)",
  "Stress, anxiety and low mood",
  "Stroke",
  "Subacromial pain syndrome",
  "Sudden infant death syndrome (SIDS)",
  "Suicide",
  "Sunburn",
  "Supraventricular tachycardia",
  "Swollen glands",
  "Syphilis",
  "Tennis elbow",
  "Testicular cancer",
  "Testicular cancer: Teenagers and young adults",
  "Testicular lumps and swellings",
  "Thirst",
  "Threadworms",
  "Thrush",
  "Thyroid cancer",
  "Thyroid cancer: Teenagers and young adults",
  "Tick bites",
  "Tinnitus",
  "Tonsillitis",
  "Tooth decay",
  "Toothache",
  "Touretteâ€™s syndrome",
  "Transient ischaemic attack (TIA)",
  "Transverse myelitis",
  "Trichomonas infection",
  "Trigeminal neuralgia",
  "Tuberculosis (TB)",
  "Type 1 diabetes",
  "Type 2 diabetes",
  "Ulcerative colitis",
  "Underactive thyroid",
  "Urinary incontinence",
  "Urinary tract infection (UTI)",
  "Urticaria (hives)",
  "Vaginal cancer",
  "Vaginal discharge",
  "Varicose eczema",
  "Varicose veins",
  "Venous leg ulcer",
  "Vertigo",
  "Vitamin B12 or folate deficiency anaemia",
  "Vulval cancer",
  "Vomiting",
  "Warts and verrucas",
  "Whiplash",
  "Whooping cough",
  "Wilmsâ€™ tumour",
  "Wolff-Parkinson-White syndrome",
  "Womb (uterus) cancer",
  "Yellow fever",
  "Zika virus"
];