List<String> allTests = [
  "Complete Blood Count (CBC)",
  "Blood Glucose Test",
  "Lipid Panel",
  "Liver Function Test (LFT)",
  "Kidney Function Test",
  "X-Ray - Chest",
  "X-Ray - Bones",
  "X-Ray - Abdomen",
  "X-Ray - Skull",
  "X-Ray - Spine",
  "Ultrasound - Abdomen",
  "Ultrasound - Pelvis",
  "Ultrasound - Pregnancy",
  "Ultrasound - Thyroid",
  "Ultrasound - Heart (Echocardiogram)",
  "Magnetic Resonance Imaging (MRI) - Brain",
  "MRI - Spine",
  "MRI - Abdomen",
  "MRI - Joints",
  "MRI - Heart",
  "MRI - Blood Vessels (MR Angiography)",
  "Computed Tomography (CT) Scan - Head",
  "CT Scan - Chest",
  "CT Scan - Abdomen",
  "CT Scan - Pelvis",
  "CT Scan - Spine",
  "CT Angiography (CTA)",
  "Mammography - Screening",
  "Mammography - Diagnostic",
  "Bone Density Scan (DEXA) - Hip",
  "Bone Density Scan (DEXA) - Spine",
  "Colonoscopy",
  "Sigmoidoscopy",
  "Gastroscopy",
  "Endoscopic Ultrasound",
  "Capsule Endoscopy",
  "Bronchoscopy",
  "Cystoscopy",
  "Electrocardiogram (ECG/EKG) - Resting",
  "ECG - Stress",
  "Ambulatory ECG (Holter Monitor)",
  "Echocardiogram - Transthoracic",
  "Echocardiogram - Transesophageal",
  "Echocardiogram - Stress",
  "Cardiac Catheterization",
  "Exercise Stress Test - Treadmill",
  "Nuclear Stress Test",
  "Cardiac MRI",
  "Cardiac CT",
  "Coronary Angiography",
  "Carotid Ultrasound",
  "Doppler Ultrasound - Blood Vessels",
  "Ankle-Brachial Index (ABI)",
  "Pulse Oximetry",
  "Pulmonary Function Test (PFT) - Spirometry",
  "PFT - Lung Volumes",
  "PFT - Diffusion Capacity",
  "Arterial Blood Gas (ABG)",
  "Fractional Exhaled Nitric Oxide (FeNO)",
  "Peak Flow Measurement",
  "Chest X-Ray",
  "CT Pulmonary Angiography (CTPA)",
  "Bronchial Provocation Test",
  "Methacholine Challenge Test",
  "Urinalysis - Routine",
  "Urinalysis - Microscopic",
  "24-Hour Urine Collection - Protein",
  "24-Hour Urine Collection - Creatinine",
  "Urine Culture",
  "Urine Pregnancy Test",
  "Stool Test - Occult Blood",
  "Stool Test - Ova and Parasites",
  "Stool Test - Culture",
  "Stool Test - Clostridium difficile",
  "Needle Biopsy - Breast",
  "Needle Biopsy - Liver",
  "Needle Biopsy - Thyroid",
  "Needle Biopsy - Lung",
  "Skin Biopsy - Punch",
  "Skin Biopsy - Shave",
  "Skin Biopsy - Excisional",
  "Bone Marrow Biopsy",
  "Karyotyping - Chromosomal Analysis",
  "DNA Sequencing - Genetic Testing",
  "Gene Panel Testing - Cancer",
  "Gene Panel Testing - Cardiovascular Disease",
  "Gene Panel Testing - Neurological Disorders",
  "Genetic Carrier Screening",
  "Whole Exome Sequencing",
  "Whole Genome Sequencing",
  "Prenatal Genetic Testing - Amniocentesis",
  "Prenatal Genetic Testing - Chorionic Villus Sampling (CVS)",
  "Thyroid Function Test - TSH",
  "Thyroid Function Test - Free T4",
  "Thyroid Function Test - Total T3",
  "Parathyroid Hormone (PTH) Test",
  "Cortisol Test - Blood",
  "Cortisol Test - Saliva",
  "Cortisol Test - Urine",
  "Adrenocorticotropic Hormone (ACTH) Test",
  "Testosterone Levels - Total",
  "Testosterone Levels - Free",
  "Estrogen Levels - Estradiol",
  "Estrogen Levels - Estrone",
  "Progesterone Levels",
  "Follicle Stimulating Hormone (FSH) Test",
  "Luteinizing Hormone (LH) Test",
  "Prolactin Test",
  "Human Chorionic Gonadotropin (HCG) Test",
  "Vitamin D Level",
  "Calcium Level",
  "Phosphorus Level",
  "Magnesium Level",
  "Electrolyte Panel - Sodium",
  "Electrolyte Panel - Potassium",
  "Electrolyte Panel - Chloride",
  "Electrolyte Panel - Bicarbonate",
  "Lipid Panel - Cholesterol",
  "Lipid Panel - Triglycerides",
  "C-Reactive Protein (CRP) Test",
  "Erythrocyte Sedimentation Rate (ESR)",
  "Antinuclear Antibody (ANA) Test",
  "Rheumatoid Factor (RF) Test",
  "Anti-Cyclic Citrullinated Peptide (Anti-CCP) Test",
  "Blood Urea Nitrogen (BUN) Test",
  "Serum Creatinine Test",
  "Creatinine Clearance Test",
  "Glomerular Filtration Rate (GFR) Test",
  "Liver Function Test (ALT)",
  "Liver Function Test (AST)",
  "Liver Function Test (ALP)",
  "Liver Function Test (Bilirubin)",
  "Liver Function Test (Albumin)",
  "Lactate Dehydrogenase (LDH) Test",
  "Hepatitis Panel",
  "HIV Test - ELISA",
  "HIV Test - Western Blot",
  "HIV Test - PCR",
  "Syphilis Test - RPR",
  "Syphilis Test - FTA-ABS",
  "Chlamydia Test - NAAT",
  "Gonorrhea Test - NAAT",
  "Herpes Simplex Virus (HSV) Test",
  "Human Papillomavirus (HPV) Test",
  "Tuberculosis Skin Test (Mantoux)",
  "Tuberculosis Blood Test (IGRA)",
  "COVID-19 PCR Test",
  "COVID-19 Rapid Antigen Test",
  "Influenza PCR Test",
  "Influenza Rapid Test",
  "Mononucleosis Test",
  "Lyme Disease Test",
  "Malaria Blood Smear",
  "Hepatitis A Test",
  "Hepatitis B Test",
  "Hepatitis C Test",
  "Blood Alcohol Test",
  "Toxicology Screen - Drugs",
  "Toxicology Screen - Poisons",
  "Lead Poisoning Test",
  "Mercury Poisoning Test",
  "Carbon Monoxide Test",
  "Electroencephalogram (EEG)",
  "Nerve Conduction Velocity (NCV) Test",
  "Electromyography (EMG)",
  "Evoked Potentials Test",
  "Sleep Study (Polysomnography)",
  "Multiple Sleep Latency Test (MSLT)",
  "Video EEG Monitoring",
  "Tilt Table Test",
  "PCR Test for Viral Infections",
  "Rapid Antigen Test for Bacterial Infections",
  "Serology Test - Antibodies",
  "Hemoglobin A1c Test",
  "Oral Glucose Tolerance Test",
  "Fasting Blood Glucose Test",
  "Glucose Challenge Test",
  "Autoimmune Disease Panel",
  "Inflammatory Marker Panel",
  "Immunoglobulin Test - IgA",
  "Immunoglobulin Test - IgG",
  "Immunoglobulin Test - IgM",
  "Blood Clotting Test - PT/INR",
  "Blood Clotting Test - aPTT",
  "D-Dimer Test",
  "Fibrinogen Test",
  "Platelet Count",
  "Bone Marrow Aspiration",
  "Chorionic Villus Sampling (CVS)",
  "Amniocentesis",
  "Cervical Biopsy",
  "Endometrial Biopsy",
  "Prostate-Specific Antigen (PSA) Test",
  "Digital Rectal Exam (DRE)",
  "Pap Smear",
  "Breast MRI",
  "Pelvic MRI",
  "Cardiac Calcium Scoring",
  "Hemoglobin Electrophoresis",
  "Serum Iron Test",
  "Total Iron-Binding Capacity (TIBC)",
  "Ferritin Test",
  "Vitamin B12 Level",
  "Folate Level",
  "Red Blood Cell Count",
  "White Blood Cell Count",
  "Platelet Count",
  "Serum Protein Electrophoresis (SPEP)",
  "Urine Protein Electrophoresis (UPEP)",
  "Haptoglobin Test",
  "Serum Amylase Test",
  "Serum Lipase Test",
  "Beta-hCG Quantitative Test",
  "Rapid Strep Test",
  "Bone Density Test",
  "Colposcopy",
  "Hysteroscopy",
  "Laparoscopy",
  "Thermography",
  "Sputum Culture",
  "Synovial Fluid Analysis",
  "Pleural Fluid Analysis",
  "Peritoneal Fluid Analysis"
];